[project]
name = "defacc"
version = "0.1.0"
description = "placeholder"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dspy>=0.1.4",
    "libclang>=18.1.1",
    "pydantic-settings>=2.0.0",
    "rank-bm25>=0.2.2",
    "inspect-ai>=0.3.148",
    "networkx>=3.4.2",
]
